"""
One-time seed script for the producer directory. Run:
    cd backend && python scripts/seed_producers.py

All names/companies are clearly fictional (per project rule: never use real
people or companies as fake investors). Running this twice is safe — it
skips any producer whose id already exists.

This dataset contains 100 producers spanning 100 countries worldwide.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.db.auth_db import Producer, SessionLocal, init_auth_db  # noqa: E402

PRODUCERS = [
    dict(id="p001", name="Selin Brenner", company="Vertex Reel Works", country="Qatar",
         languages="Arabic,English", genres="Comedy,Crime", investment_min=700000, investment_max=3200000,
         films_produced=26, success_rate_pct=92, avg_roi_x="1.4x", rating="4.3"),
    dict(id="p002", name="Tobias Castillo", company="Delta Frame House", country="Kuwait",
         languages="Arabic,English", genres="Musical,Fantasy", investment_min=600000, investment_max=3600000,
         films_produced=18, success_rate_pct=89, avg_roi_x="1.5x", rating="5.0"),
    dict(id="p003", name="Neda Okonkwo", company="Silver Frame Co", country="Netherlands",
         languages="Dutch,English", genres="Drama,Sci-Fi", investment_min=300000, investment_max=4300000,
         films_produced=11, success_rate_pct=91, avg_roi_x="2.0x", rating="4.5"),
    dict(id="p004", name="Aroha Kobayashi", company="Granite Frame House", country="Ireland",
         languages="English", genres="Animation,Drama", investment_min=1000000, investment_max=5000000,
         films_produced=9, success_rate_pct=95, avg_roi_x="2.3x", rating="4.8"),
    dict(id="p005", name="Talia Petrova", company="Atlas Media House", country="Laos",
         languages="Lao,English", genres="Thriller,Horror", investment_min=200000, investment_max=4200000,
         films_produced=29, success_rate_pct=86, avg_roi_x="2.6x", rating="4.8"),
    dict(id="p006", name="Ari Mensah", company="Lantern Frame House", country="Thailand",
         languages="Thai,English", genres="Crime,Animation", investment_min=900000, investment_max=2400000,
         films_produced=10, success_rate_pct=89, avg_roi_x="2.3x", rating="4.6"),
    dict(id="p007", name="Xola Barreto", company="Northern Productions", country="Canada",
         languages="English,French", genres="Romance,Horror", investment_min=200000, investment_max=1200000,
         films_produced=17, success_rate_pct=87, avg_roi_x="1.5x", rating="4.4"),
    dict(id="p008", name="Deepa Laine", company="Silver Story House", country="Croatia",
         languages="Croatian,English", genres="Horror,Sci-Fi", investment_min=800000, investment_max=5800000,
         films_produced=10, success_rate_pct=82, avg_roi_x="2.1x", rating="5.0"),
    dict(id="p009", name="Farah Kowalski", company="Granite Lens Collective", country="Singapore",
         languages="English,Mandarin", genres="Fantasy,Documentary", investment_min=350000, investment_max=3350000,
         films_produced=30, success_rate_pct=84, avg_roi_x="2.2x", rating="4.5"),
    dict(id="p010", name="Ilse Anand", company="Ember Motion Co", country="Jamaica",
         languages="English", genres="Animation,Horror", investment_min=250000, investment_max=1750000,
         films_produced=13, success_rate_pct=80, avg_roi_x="1.7x", rating="4.7"),
    dict(id="p011", name="Mei Hartmann", company="River Pictures", country="Greece",
         languages="Greek,English", genres="Sci-Fi,Crime", investment_min=200000, investment_max=1700000,
         films_produced=8, success_rate_pct=79, avg_roi_x="2.4x", rating="4.3"),
    dict(id="p012", name="Rosa Sokolov", company="Meridian Motion Co", country="Saudi Arabia",
         languages="Arabic,English", genres="Comedy,Animation", investment_min=300000, investment_max=4300000,
         films_produced=24, success_rate_pct=96, avg_roi_x="1.9x", rating="4.8"),
    dict(id="p013", name="Cyrus Torres", company="Crescent Films", country="Algeria",
         languages="Arabic,French", genres="Crime,Documentary", investment_min=500000, investment_max=3000000,
         films_produced=19, success_rate_pct=92, avg_roi_x="2.4x", rating="4.2"),
    dict(id="p014", name="Gudrun Holm", company="Crescent Pictures", country="Senegal",
         languages="French,English", genres="Documentary,Romance", investment_min=250000, investment_max=1750000,
         films_produced=12, success_rate_pct=84, avg_roi_x="2.0x", rating="4.3"),
    dict(id="p015", name="Nadia Sokolov", company="Copper Cinema Group", country="Estonia",
         languages="Estonian,English", genres="Sci-Fi,Horror", investment_min=800000, investment_max=1800000,
         films_produced=7, success_rate_pct=95, avg_roi_x="2.4x", rating="5.0"),
    dict(id="p016", name="Uma Ferreira", company="Coastal Media House", country="Nigeria",
         languages="English,Yoruba", genres="Horror,Musical", investment_min=350000, investment_max=5350000,
         films_produced=18, success_rate_pct=79, avg_roi_x="1.4x", rating="4.2"),
    dict(id="p017", name="Ximena Kowalski", company="Copper Frame House", country="Japan",
         languages="Japanese,English", genres="Documentary,Animation", investment_min=1000000, investment_max=5000000,
         films_produced=21, success_rate_pct=82, avg_roi_x="1.5x", rating="4.4"),
    dict(id="p018", name="Priya Falcao", company="Amber Screen Works", country="Hong Kong",
         languages="Cantonese,English", genres="Drama,Romance", investment_min=200000, investment_max=1200000,
         films_produced=24, success_rate_pct=93, avg_roi_x="1.9x", rating="4.9"),
    dict(id="p019", name="Chidi Nair", company="Granite Films", country="Latvia",
         languages="Latvian,English", genres="Thriller,Sci-Fi", investment_min=900000, investment_max=1900000,
         films_produced=27, success_rate_pct=85, avg_roi_x="1.8x", rating="5.0"),
    dict(id="p020", name="Deepa Krause", company="Summit Productions", country="Australia",
         languages="English", genres="Drama,Fantasy", investment_min=250000, investment_max=2750000,
         films_produced=27, success_rate_pct=96, avg_roi_x="2.0x", rating="4.5"),
    dict(id="p021", name="Milo Owusu", company="Meridian Story House", country="Israel",
         languages="Hebrew,English", genres="Romance,Comedy", investment_min=400000, investment_max=2900000,
         films_produced=10, success_rate_pct=87, avg_roi_x="1.8x", rating="4.9"),
    dict(id="p022", name="Isabela Reyes", company="Copper Productions", country="Lithuania",
         languages="Lithuanian,English", genres="Fantasy,Sci-Fi", investment_min=250000, investment_max=3250000,
         films_produced=12, success_rate_pct=94, avg_roi_x="1.6x", rating="4.9"),
    dict(id="p023", name="Declan Krause", company="Ember Frame House", country="Ethiopia",
         languages="Amharic,English", genres="Thriller,Horror", investment_min=800000, investment_max=4800000,
         films_produced=15, success_rate_pct=94, avg_roi_x="1.2x", rating="4.9"),
    dict(id="p024", name="Sanaa Osman", company="Crescent Cinematics", country="Serbia",
         languages="Serbian,English", genres="Thriller,Action", investment_min=250000, investment_max=1250000,
         films_produced=29, success_rate_pct=95, avg_roi_x="1.4x", rating="4.4"),
    dict(id="p025", name="Kofi Duarte", company="Highland Vision Studios", country="Kazakhstan",
         languages="Kazakh,Russian", genres="Crime,Action", investment_min=800000, investment_max=3300000,
         films_produced=14, success_rate_pct=79, avg_roi_x="1.3x", rating="4.5"),
    dict(id="p026", name="Otto Ishikawa", company="Northern Reel Works", country="New Zealand",
         languages="English", genres="Thriller,Crime", investment_min=400000, investment_max=1900000,
         films_produced=29, success_rate_pct=92, avg_roi_x="2.0x", rating="4.5"),
    dict(id="p027", name="August Petrova", company="Silver Cinematics", country="UK",
         languages="English", genres="Musical,Thriller", investment_min=800000, investment_max=1800000,
         films_produced=17, success_rate_pct=96, avg_roi_x="2.0x", rating="4.5"),
    dict(id="p028", name="Haruto Larsen", company="Ember Cinematics", country="Iceland",
         languages="Icelandic,English", genres="Drama,Romance", investment_min=350000, investment_max=4350000,
         films_produced=13, success_rate_pct=81, avg_roi_x="1.7x", rating="4.6"),
    dict(id="p029", name="Cyrus Byun", company="Amber Studios", country="India",
         languages="English,Hindi,Tamil", genres="Comedy,Thriller", investment_min=300000, investment_max=2800000,
         films_produced=6, success_rate_pct=83, avg_roi_x="2.2x", rating="4.5"),
    dict(id="p030", name="Cyrus Corvin", company="Amber Frame Co", country="Russia",
         languages="Russian,English", genres="Comedy,Action", investment_min=300000, investment_max=5300000,
         films_produced=28, success_rate_pct=81, avg_roi_x="1.7x", rating="4.2"),
    dict(id="p031", name="Rafi de Vries", company="Highland Lens Collective", country="Lebanon",
         languages="Arabic,French", genres="Horror,Romance", investment_min=400000, investment_max=5400000,
         films_produced=13, success_rate_pct=85, avg_roi_x="1.2x", rating="4.4"),
    dict(id="p032", name="Kian Sokolov", company="Silver Frame Co", country="France",
         languages="French,English", genres="Action,Romance", investment_min=1000000, investment_max=4000000,
         films_produced=18, success_rate_pct=95, avg_roi_x="1.7x", rating="4.2"),
    dict(id="p033", name="Milo Andersen", company="Summit Frame House", country="Pakistan",
         languages="Urdu,English", genres="Drama,Sci-Fi", investment_min=900000, investment_max=3400000,
         films_produced=17, success_rate_pct=88, avg_roi_x="1.8x", rating="5.0"),
    dict(id="p034", name="Ines Nakamura", company="Summit Cinema Group", country="Fiji",
         languages="English", genres="Action,Drama", investment_min=600000, investment_max=1600000,
         films_produced=22, success_rate_pct=95, avg_roi_x="2.2x", rating="5.0"),
    dict(id="p035", name="Saoirse Corvin", company="Highland Reel Works", country="Cameroon",
         languages="French,English", genres="Documentary,Sci-Fi", investment_min=1000000, investment_max=3000000,
         films_produced=25, success_rate_pct=88, avg_roi_x="2.1x", rating="4.3"),
    dict(id="p036", name="Sanaa Winter", company="Atlas Vision Studios", country="Dominican Republic",
         languages="Spanish", genres="Documentary,Romance", investment_min=600000, investment_max=4600000,
         films_produced=15, success_rate_pct=95, avg_roi_x="1.4x", rating="4.5"),
    dict(id="p037", name="Leif Freire", company="Amber Cinematics", country="Colombia",
         languages="Spanish", genres="Thriller,Fantasy", investment_min=900000, investment_max=2900000,
         films_produced=18, success_rate_pct=95, avg_roi_x="2.4x", rating="4.4"),
    dict(id="p038", name="Kofi Kaur", company="Summit Productions", country="Sri Lanka",
         languages="Sinhala,English", genres="Crime,Romance", investment_min=700000, investment_max=3200000,
         films_produced=20, success_rate_pct=84, avg_roi_x="1.9x", rating="4.8"),
    dict(id="p039", name="Zane Demir", company="Meridian Films", country="South Korea",
         languages="Korean,English", genres="Action,Animation", investment_min=1000000, investment_max=5000000,
         films_produced=25, success_rate_pct=88, avg_roi_x="1.3x", rating="5.0"),
    dict(id="p040", name="Rosa Freire", company="Atlas Cinema Group", country="Panama",
         languages="Spanish,English", genres="Comedy,Thriller", investment_min=200000, investment_max=1200000,
         films_produced=13, success_rate_pct=93, avg_roi_x="2.1x", rating="4.8"),
    dict(id="p041", name="Amadou Aydin", company="Lantern Productions", country="Cambodia",
         languages="Khmer,English", genres="Comedy,Documentary", investment_min=700000, investment_max=3200000,
         films_produced=13, success_rate_pct=82, avg_roi_x="2.1x", rating="4.2"),
    dict(id="p042", name="Uma Mensah", company="Onyx Media House", country="Indonesia",
         languages="Indonesian,English", genres="Comedy,Thriller", investment_min=800000, investment_max=3300000,
         films_produced=7, success_rate_pct=95, avg_roi_x="1.5x", rating="4.9"),
    dict(id="p043", name="Amadou Sato", company="Copper Vision Studios", country="Paraguay",
         languages="Spanish", genres="Animation,Musical", investment_min=900000, investment_max=2900000,
         films_produced=30, success_rate_pct=92, avg_roi_x="2.1x", rating="4.8"),
    dict(id="p044", name="Ari Vogel", company="Delta Motion Co", country="Iraq",
         languages="Arabic,English", genres="Thriller,Horror", investment_min=700000, investment_max=2700000,
         films_produced=30, success_rate_pct=85, avg_roi_x="2.4x", rating="4.4"),
    dict(id="p045", name="Xola Iwata", company="Ivory Vision Studios", country="Morocco",
         languages="Arabic,French", genres="Comedy,Action", investment_min=700000, investment_max=1700000,
         films_produced=28, success_rate_pct=87, avg_roi_x="1.5x", rating="4.5"),
    dict(id="p046", name="Torsten Laine", company="Harbor Studios", country="Czech Republic",
         languages="Czech,English", genres="Comedy,Documentary", investment_min=300000, investment_max=4300000,
         films_produced=12, success_rate_pct=80, avg_roi_x="1.8x", rating="4.5"),
    dict(id="p047", name="Elin Aydin", company="Golden Cinema Group", country="Kenya",
         languages="English,Swahili", genres="Documentary,Musical", investment_min=900000, investment_max=4900000,
         films_produced=6, success_rate_pct=96, avg_roi_x="1.7x", rating="4.2"),
    dict(id="p048", name="Vera Marchetti", company="Onyx Media House", country="South Africa",
         languages="English,Afrikaans", genres="Documentary,Animation", investment_min=800000, investment_max=5800000,
         films_produced=25, success_rate_pct=85, avg_roi_x="1.9x", rating="4.4"),
    dict(id="p049", name="Kenji Oduya", company="Marble Reel Works", country="Norway",
         languages="Norwegian,English", genres="Crime,Musical", investment_min=600000, investment_max=4600000,
         films_produced=11, success_rate_pct=92, avg_roi_x="2.5x", rating="5.0"),
    dict(id="p050", name="Salma Oduya", company="Marble Productions", country="Georgia",
         languages="Georgian,English", genres="Fantasy,Crime", investment_min=200000, investment_max=1200000,
         films_produced=26, success_rate_pct=91, avg_roi_x="1.4x", rating="4.6"),
    dict(id="p051", name="Camille Kowalski", company="Marble Reel Works", country="Chile",
         languages="Spanish", genres="Comedy,Horror", investment_min=500000, investment_max=2500000,
         films_produced=30, success_rate_pct=90, avg_roi_x="1.6x", rating="5.0"),
    dict(id="p052", name="Odette Hassan", company="Silver Motion Co", country="Austria",
         languages="German,English", genres="Drama,Animation", investment_min=200000, investment_max=2200000,
         films_produced=13, success_rate_pct=80, avg_roi_x="2.3x", rating="4.7"),
    dict(id="p053", name="Uma Oduya", company="River Cinema Group", country="Peru",
         languages="Spanish", genres="Drama,Fantasy", investment_min=300000, investment_max=1800000,
         films_produced=10, success_rate_pct=93, avg_roi_x="2.1x", rating="4.7"),
    dict(id="p054", name="Selin Kobayashi", company="Vertex Frame House", country="UAE",
         languages="Arabic,English", genres="Romance,Thriller", investment_min=900000, investment_max=3900000,
         films_produced=29, success_rate_pct=81, avg_roi_x="2.3x", rating="4.3"),
    dict(id="p055", name="Petra Mensah", company="Summit Pictures", country="Uganda",
         languages="English,Swahili", genres="Action,Fantasy", investment_min=1000000, investment_max=3500000,
         films_produced=18, success_rate_pct=84, avg_roi_x="1.3x", rating="4.8"),
    dict(id="p056", name="Elif Krause", company="Crescent Story House", country="Bangladesh",
         languages="Bengali,English", genres="Action,Crime", investment_min=900000, investment_max=5900000,
         films_produced=9, success_rate_pct=96, avg_roi_x="2.3x", rating="4.5"),
    dict(id="p057", name="Tomas Osman", company="Ember Films", country="Mexico",
         languages="Spanish", genres="Animation,Crime", investment_min=500000, investment_max=1500000,
         films_produced=19, success_rate_pct=93, avg_roi_x="1.3x", rating="5.0"),
    dict(id="p058", name="Dagny Amara", company="Vertex Studios", country="Taiwan",
         languages="Mandarin,English", genres="Documentary,Thriller", investment_min=800000, investment_max=4800000,
         films_produced=14, success_rate_pct=95, avg_roi_x="2.3x", rating="4.6"),
    dict(id="p059", name="Rina Hartmann", company="Sunset Reel Works", country="Belgium",
         languages="Dutch,French", genres="Comedy,Sci-Fi", investment_min=400000, investment_max=2900000,
         films_produced=13, success_rate_pct=92, avg_roi_x="2.0x", rating="4.7"),
    dict(id="p060", name="Talia Oduya", company="Ivory Lens Collective", country="Ghana",
         languages="English", genres="Romance,Thriller", investment_min=700000, investment_max=2200000,
         films_produced=17, success_rate_pct=86, avg_roi_x="1.7x", rating="4.9"),
    dict(id="p061", name="Nina Sokolov", company="Delta Pictures", country="Iran",
         languages="Persian,English", genres="Animation,Comedy", investment_min=250000, investment_max=1750000,
         films_produced=29, success_rate_pct=91, avg_roi_x="1.9x", rating="4.8"),
    dict(id="p062", name="Luka Lindgren", company="Lantern Story House", country="Azerbaijan",
         languages="Azerbaijani,English", genres="Horror,Musical", investment_min=200000, investment_max=1200000,
         films_produced=15, success_rate_pct=85, avg_roi_x="1.8x", rating="4.4"),
    dict(id="p063", name="Hadi Falcao", company="Ember Motion Co", country="Poland",
         languages="Polish,English", genres="Animation,Musical", investment_min=500000, investment_max=3000000,
         films_produced=29, success_rate_pct=95, avg_roi_x="1.7x", rating="4.8"),
    dict(id="p064", name="Anaya Larsen", company="Sunset Cinema Group", country="Spain",
         languages="Spanish,English", genres="Sci-Fi,Comedy", investment_min=500000, investment_max=1500000,
         films_produced=29, success_rate_pct=95, avg_roi_x="2.5x", rating="4.8"),
    dict(id="p065", name="Diego Yilmaz", company="Amber Motion Co", country="China",
         languages="Mandarin,English", genres="Action,Fantasy", investment_min=800000, investment_max=3800000,
         films_produced=15, success_rate_pct=81, avg_roi_x="2.4x", rating="4.4"),
    dict(id="p066", name="Enzo Andersen", company="Atlas Pictures", country="Venezuela",
         languages="Spanish", genres="Musical,Animation", investment_min=300000, investment_max=2300000,
         films_produced=7, success_rate_pct=79, avg_roi_x="2.0x", rating="4.8"),
    dict(id="p067", name="Tariq Vasquez", company="Onyx Motion Co", country="Rwanda",
         languages="English,French", genres="Sci-Fi,Drama", investment_min=900000, investment_max=2900000,
         films_produced=21, success_rate_pct=93, avg_roi_x="1.8x", rating="4.3"),
    dict(id="p068", name="Camille Hassan", company="Ivory Films", country="Cuba",
         languages="Spanish", genres="Sci-Fi,Documentary", investment_min=700000, investment_max=1700000,
         films_produced=24, success_rate_pct=79, avg_roi_x="1.4x", rating="4.8"),
    dict(id="p069", name="Sanaa Laine", company="River Films", country="Ecuador",
         languages="Spanish", genres="Animation,Documentary", investment_min=900000, investment_max=3900000,
         films_produced=25, success_rate_pct=85, avg_roi_x="2.3x", rating="4.5"),
    dict(id="p070", name="Vikram Marchetti", company="Summit Media House", country="Denmark",
         languages="Danish,English", genres="Action,Fantasy", investment_min=900000, investment_max=1900000,
         films_produced=25, success_rate_pct=81, avg_roi_x="2.5x", rating="4.4"),
    dict(id="p071", name="Selin Kowalski", company="Meridian Films", country="Slovakia",
         languages="Slovak,English", genres="Thriller,Comedy", investment_min=300000, investment_max=3300000,
         films_produced=8, success_rate_pct=83, avg_roi_x="1.2x", rating="4.6"),
    dict(id="p072", name="Aroha Lindgren", company="Atlas Pictures", country="Tanzania",
         languages="Swahili,English", genres="Comedy,Action", investment_min=400000, investment_max=4400000,
         films_produced=20, success_rate_pct=80, avg_roi_x="2.2x", rating="4.9"),
    dict(id="p073", name="Yara Mota", company="Summit Vision Studios", country="Bolivia",
         languages="Spanish", genres="Comedy,Documentary", investment_min=250000, investment_max=3250000,
         films_produced=13, success_rate_pct=82, avg_roi_x="2.5x", rating="4.9"),
    dict(id="p074", name="Isabela Nair", company="Coastal Frame Co", country="Finland",
         languages="Finnish,English", genres="Action,Fantasy", investment_min=900000, investment_max=2900000,
         films_produced=20, success_rate_pct=81, avg_roi_x="1.9x", rating="4.4"),
    dict(id="p075", name="Malia Novak", company="Granite Screen Works", country="USA",
         languages="English", genres="Horror,Musical", investment_min=250000, investment_max=3250000,
         films_produced=7, success_rate_pct=91, avg_roi_x="2.2x", rating="4.7"),
    dict(id="p076", name="Lena Okafor", company="River Vision Studios", country="Mongolia",
         languages="Mongolian,English", genres="Fantasy,Musical", investment_min=200000, investment_max=5200000,
         films_produced=27, success_rate_pct=86, avg_roi_x="2.0x", rating="4.8"),
    dict(id="p077", name="Lars Lindgren", company="Granite Vision Studios", country="Guatemala",
         languages="Spanish", genres="Horror,Action", investment_min=300000, investment_max=3300000,
         films_produced=19, success_rate_pct=93, avg_roi_x="2.6x", rating="4.6"),
    dict(id="p078", name="Cyrus Weber", company="Cedar Vision Studios", country="Malaysia",
         languages="Malay,English", genres="Sci-Fi,Thriller", investment_min=500000, investment_max=3000000,
         films_produced=28, success_rate_pct=93, avg_roi_x="1.6x", rating="5.0"),
    dict(id="p079", name="Viktor Adeyemi", company="Golden Motion Co", country="Tunisia",
         languages="Arabic,French", genres="Sci-Fi,Romance", investment_min=400000, investment_max=2400000,
         films_produced=9, success_rate_pct=90, avg_roi_x="2.4x", rating="4.9"),
    dict(id="p080", name="Marisol Osman", company="Delta Motion Co", country="Philippines",
         languages="English,Tagalog", genres="Documentary,Drama", investment_min=350000, investment_max=3350000,
         films_produced=17, success_rate_pct=93, avg_roi_x="2.1x", rating="4.8"),
    dict(id="p081", name="Kofi Novak", company="Delta Studios", country="Zambia",
         languages="English", genres="Action,Horror", investment_min=700000, investment_max=1700000,
         films_produced=6, success_rate_pct=85, avg_roi_x="2.2x", rating="4.4"),
    dict(id="p082", name="August Adeyemi", company="Horizon Films", country="Switzerland",
         languages="German,French,English", genres="Comedy,Sci-Fi", investment_min=700000, investment_max=1700000,
         films_produced=26, success_rate_pct=82, avg_roi_x="1.9x", rating="4.8"),
    dict(id="p083", name="Neda Novak", company="Horizon Lens Collective", country="Armenia",
         languages="Armenian,English", genres="Horror,Musical", investment_min=350000, investment_max=2850000,
         films_produced=23, success_rate_pct=82, avg_roi_x="1.7x", rating="4.9"),
    dict(id="p084", name="Neda Sato", company="Silver Frame House", country="Uruguay",
         languages="Spanish", genres="Documentary,Romance", investment_min=800000, investment_max=2800000,
         films_produced=6, success_rate_pct=87, avg_roi_x="2.2x", rating="4.9"),
    dict(id="p085", name="Riya Osman", company="Ivory Lens Collective", country="Slovenia",
         languages="Slovenian,English", genres="Thriller,Horror", investment_min=800000, investment_max=3300000,
         films_produced=17, success_rate_pct=88, avg_roi_x="2.0x", rating="4.6"),
    dict(id="p086", name="Amadou Costa", company="Highland Story House", country="Jordan",
         languages="Arabic,English", genres="Comedy,Fantasy", investment_min=600000, investment_max=2100000,
         films_produced=30, success_rate_pct=91, avg_roi_x="1.3x", rating="4.8"),
    dict(id="p087", name="Oren Rossi", company="Marble Vision Studios", country="Ukraine",
         languages="Ukrainian,English", genres="Crime,Thriller", investment_min=700000, investment_max=1700000,
         films_produced=10, success_rate_pct=94, avg_roi_x="2.6x", rating="4.5"),
    dict(id="p088", name="Noor Moreno", company="Crescent Screen Works", country="Hungary",
         languages="Hungarian,English", genres="Horror,Drama", investment_min=300000, investment_max=2800000,
         films_produced=26, success_rate_pct=82, avg_roi_x="1.3x", rating="4.8"),
    dict(id="p089", name="Milo Duarte", company="Echo Story House", country="Honduras",
         languages="Spanish", genres="Documentary,Crime", investment_min=250000, investment_max=5250000,
         films_produced=16, success_rate_pct=95, avg_roi_x="1.7x", rating="4.5"),
    dict(id="p090", name="Pia Vance", company="Delta Pictures", country="Myanmar",
         languages="Burmese,English", genres="Fantasy,Sci-Fi", investment_min=350000, investment_max=4350000,
         films_produced=27, success_rate_pct=87, avg_roi_x="2.6x", rating="4.8"),
    dict(id="p091", name="Nia Haddad", company="Onyx Vision Studios", country="Argentina",
         languages="Spanish", genres="Musical,Sci-Fi", investment_min=700000, investment_max=2200000,
         films_produced=28, success_rate_pct=87, avg_roi_x="2.5x", rating="4.2"),
    dict(id="p092", name="Zane Nair", company="Atlas Reel Works", country="Vietnam",
         languages="Vietnamese,English", genres="Romance,Documentary", investment_min=300000, investment_max=1800000,
         films_produced=22, success_rate_pct=91, avg_roi_x="2.0x", rating="4.8"),
    dict(id="p093", name="Farah Andersen", company="Silver Productions", country="Bulgaria",
         languages="Bulgarian,English", genres="Documentary,Fantasy", investment_min=1000000, investment_max=2500000,
         films_produced=21, success_rate_pct=96, avg_roi_x="1.4x", rating="4.6"),
    dict(id="p094", name="Zara Amara", company="Sunset Vision Studios", country="Germany",
         languages="German,English", genres="Drama,Horror", investment_min=400000, investment_max=4400000,
         films_produced=23, success_rate_pct=83, avg_roi_x="1.3x", rating="5.0"),
    dict(id="p095", name="Kasper Marchetti", company="Lantern Media House", country="Uzbekistan",
         languages="Uzbek,Russian", genres="Musical,Action", investment_min=700000, investment_max=5700000,
         films_produced=15, success_rate_pct=84, avg_roi_x="2.6x", rating="4.9"),
    dict(id="p096", name="Kwame Ferreira", company="Marble Productions", country="Ivory Coast",
         languages="French,English", genres="Romance,Fantasy", investment_min=400000, investment_max=4400000,
         films_produced=15, success_rate_pct=78, avg_roi_x="2.6x", rating="4.7"),
    dict(id="p097", name="Otto Reyes", company="Summit Lens Collective", country="Costa Rica",
         languages="Spanish", genres="Crime,Drama", investment_min=900000, investment_max=4900000,
         films_produced=21, success_rate_pct=87, avg_roi_x="2.3x", rating="4.4"),
    dict(id="p098", name="Vera de Vries", company="Lantern Cinema Group", country="Italy",
         languages="Italian,English", genres="Fantasy,Action", investment_min=1000000, investment_max=6000000,
         films_produced=29, success_rate_pct=82, avg_roi_x="2.1x", rating="4.9"),
    dict(id="p099", name="Feras Ishikawa", company="Atlas Frame Co", country="Nepal",
         languages="Nepali,English", genres="Horror,Drama", investment_min=900000, investment_max=2900000,
         films_produced=29, success_rate_pct=82, avg_roi_x="1.3x", rating="4.4"),
    dict(id="p100", name="Tobias Aydin", company="Coastal Cinema Group", country="Sweden",
         languages="Swedish,English", genres="Thriller,Animation", investment_min=500000, investment_max=3500000,
         films_produced=22, success_rate_pct=86, avg_roi_x="2.4x", rating="4.4"),
]


def main():
    init_auth_db()
    db = SessionLocal()
    added = 0
    try:
        for data in PRODUCERS:
            exists = db.query(Producer).filter(Producer.id == data["id"]).first()
            if exists:
                continue
            db.add(Producer(**data))
            added += 1
        db.commit()
    finally:
        db.close()
    print(f"✅ Seeded {added} new producers ({len(PRODUCERS)} total in dataset).")


if __name__ == "__main__":
    main()